---
- name: API request vault auth token
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/auth/userpass/login/{{ vault_username }}"
    method: PUT
    body_format: form-urlencoded
    body:
      password: "{{ vault_password }}"
    headers:
      Content-Type: application/json
      X-Vault-Request: true
  register: vault_api_data_token
  delegate_to: localhost

- name: Debug api token
  ansible.builtin.debug:
    msg: "Token received from vault server: {{ vault_api_data_token.json.client_token }}"
  when: debug | bool