---
- name: API request vault auth token
  ansible.builtin.uri:
    return_content: yes
    validate_certs: false
    url: "{{ vault_url }}/v1/auth/userpass/login/{{ vault_username }}"
    method: PUT
    body_format: form-urlencoded
    body:
      password: "{{ vault_password }}"
    headers:
      X-Vault-Request: true
  register: vault_api_data_token
  delegate_to: localhost

- name: Save request vault api token to vars
  ansible.builtin.set_fact:
    vault_token: "{{ vault_api_data_token.json.auth.client_token }}"

- name: Debug api token
  ansible.builtin.debug:
    msg: "Token received from vault server: {{ vault_token }}"
  when: debug | bool