---
- name: Enable vault secret engine for CA
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ vault_ca_path }}"
    method: POST
    status_code: 204
    body_format: json
    body:
      type: pki
      description: ""
      config: 
        options: null
        default_lease_ttl: 0s
        max_lease_ttl: 0s
        force_no_cache: false
      local: false
      seal_wrap: false
      external_entropy_access: false
      options: null
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Tune vault secret engine CA configuration
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ vault_ca_path }}/tune"
    method: POST
    status_code: 204
    body_format: json
    body:
      options: null
      default_lease_ttl: ""
      max_lease_ttl: "{{ vault_ca_max_lease_ttl }}"
      force_no_cache: false
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create ca root certificate
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/root/generate/internal"
    method: PUT
    status_code: 200
    body_format: json
    body:
      common_name: "{{ vault_ca_cert_common_name }}"
      key_bits: "{{ vault_ca_cert_key_bits }}"
      organization: "{{ vault_ca_cert_organization }}"
      ou: "{{ vault_ca_cert_ou }}"
      ttl: "{{ vault_ca_cert_ttl }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create ca and crl distribution points
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/config/urls"
    method: PUT
    status_code: 204
    body_format: json
    body:
      crl_distribution_points: "{{ vault_url }}/v1/pki/crl"
      issuing_certificates: "{{ vault_url }}/v1/pki/ca"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create ca role (general certificate policy)
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/roles/{{ vault_ca_cert_role_name }}"
    method: PUT
    status_code: 204
    body_format: json
    body:
      allow_subdomains: "{{ vault_ca_role_allow_subdomains }}"
      allowed_domains: "{{ vault_ca_role_allowed_domains }}"
      max_ttl: "{{ vault_ca_role_max_ttl }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Load vault server podman-profile
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - 'vault-server.yaml'
      paths:
        - 'vars'
  when: vault_ca_install_vault_cert | bool

- name: "Request and sign certificate for {{ ansible_fqdn }} (vault webinterface)"
  ansible.builtin.uri:
    return_content: yes
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/issue/{{ vault_ca_cert_role_name }}"
    method: PUT
    status_code: 200
    body_format: json
    body:
      common_name: "{{ ansible_fqdn }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  register: vault_generated_cert_vault
  delegate_to: localhost
  when: vault_ca_install_vault_cert | bool

- name: "Installing public key to {{ mounts.certs.host }}/{{ cert_crt_name }}"
  ansible.builtin.copy:
    content: "{{ vault_generated_cert_vault.json.data.certificate }}"
    dest: "{{ mounts.certs.host }}/{{ cert_crt_name }}"
  when: vault_ca_install_vault_cert | bool

- name: "Installing private key to {{ mounts.certs.host }}/{{ cert_key_name }}"
  ansible.builtin.copy:
    content: "{{ vault_generated_cert_vault.json.data.private_key }}"
    dest: "{{ mounts.certs.host }}/{{ cert_key_name }}"
  when: vault_ca_install_vault_cert | bool

- name: Note
  ansible.builtin.debug:
    msg: "Please install the ca key on target system so that certificates classified as trusted or you can run this role that automaticly installs the ca cert on your system"

- name: CA key linux link
  ansible.builtin.debug:
    msg: "CA key for linux - download here: {{ vault_url }}/v1/{{ vault_ca_path }}/ca/pem"

- name: CA key windows link
  ansible.builtin.debug:
    msg: "CA key for windows - download here: {{ vault_url }}/v1/{{ vault_ca_path }}/ca"