---
- name: Create LDAP auth
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/auth/{{ item.name }}"
    method: POST
    status_code: [204, 400]
    body_format: json
    body:
      type: ldap
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: "{{ vault_api_executor }}"

- name: Configure LDAP auth
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/auth/ldap/config"
    method: POST
    status_code: [204, 400]
    body_format: json
    body:
      url: "{{ item.url }}"
      case_sensitive_names: "{{ item.case_sensitive_names }}"
      certificate: "{{ item.certificate }}"
      binddn: "{{ item.binddn }}"
      bindpass: "{{ item.bindpass }}"
      userdn: "{{ item.userdn }}"
      deny_null_bind: "{{ item.deny_null_bind }}"
      groupfilter: "{{ item.groupfilter }}"
      groupdn: "{{ item.groupdn }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: "{{ vault_api_executor }}"

- name: Add LDAP group-policy mapping
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/auth/ldap/groups/{{ item.group_policy_mapping_name }}"
    method: POST
    status_code: [204, 400]
    body_format: json
    body:
      policies: "{{ item.group_policy_mapping_policies }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: "{{ vault_api_executor }}"