---
- name: Enable userpass auth engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/auth/userpass"
    method: POST
    status_code: [200, 400, 204]
    body_format: json
    body:
      type: userpass
      description: ""
      config: 
        options: null
        default_lease_ttl: 0s
        max_lease_ttl: 0s
        force_no_cache: false
      local: false
      seal_wrap: false
      external_entropy_access: false
      options: null
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: "{{ vault_api_executor }}"


- name: Create admin policy
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/policies/acl/admin"
    method: PUT
    status_code: 204
    body_format: json
    body:
      {"policy":"# Read system health check\npath \"sys/health\"\n{\n  capabilities = [\"read\", \"sudo\"]\n}\n\n# Create and manage ACL policies broadly across Vault\n\n# List existing policies\npath \"sys/policies/acl\"\n{\n  capabilities = [\"list\"]\n}\n\n# Create and manage ACL policies\npath \"sys/policies/acl/*\"\n{\n  capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"]\n}\n\n# Enable and manage authentication methods broadly across Vault\n\n# Manage auth methods broadly across Vault\npath \"auth/*\"\n{\n  capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"]\n}\n\n# Create, update, and delete auth methods\npath \"sys/auth/*\"\n{\n  capabilities = [\"create\", \"update\", \"delete\", \"sudo\"]\n}\n\n# List auth methods\npath \"sys/auth\"\n{\n  capabilities = [\"read\"]\n}\n\n# Enable and manage the key/value secrets engine at  path\n\n# List, create, update, and delete key/value secrets\npath \"secret/*\"\n{\n  capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"]\n}\n\n# Manage secrets engines\npath \"sys/mounts/*\"\n{\n  capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"]\n}\n\n# List existing secrets engines.\npath \"sys/mounts\"\n{\n  capabilities = [\"read\"]\n}\n"}
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: "{{ vault_api_executor }}"

- name: Create local vault user(s) via userpass engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/auth/userpass/users/{{ item.name }}"
    method: PUT
    status_code: 204
    body_format: json
    body:
      password: "{{ item.password }}"
      policies: "{{ item.policies }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  with_items:
    - "{{ vault_crate_user_data }}"
  delegate_to: "{{ vault_api_executor }}"