---
- name: Create namespace
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/namespaces/{{ item.namespace }}"
    method: POST
    status_code: [200, 400]
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: "{{ vault_api_executor }}"
  with_items:
    - "{{ vault_kv_write_data }}"
  when: item.namespace is defined and create_vault_namespace|bool

- name: Create KV database
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ item.secret_engine }}"
    method: POST
    status_code: [204, 400]
    body_format: json
    body:
      type: kv
      description: ""
      config:
        options: null
        default_lease_ttl: 0s
        max_lease_ttl: 0s
        force_no_cache: false
      local: false
      seal_wrap: false
      external_entropy_access: false
      options:
        version: 2
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
      X-Vault-Namespace: "{{ item.namespace | default(omit) }}"
  delegate_to: "{{ vault_api_executor }}"
  with_items:
    - "{{ vault_kv_write_data | default(omit) }}"
    - "{{ vault_kv_write_file_data | default(omit) }}"
