---
- name: "Write data to {{ vault_ceate_kv_db_name }}/{{ vault_kv_write_secret_name }}"
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ceate_kv_db_name }}/{{ vault_kv_write_secret_name }}"
    method: PUT
    status_code: 200
    body_format: json
    body: "{{ lookup('template', './vault-kv-write-secret.json.j2') }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Write file data in base64 to kv secret engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ item.secret_engine }}/{{ item.secret_name }}"
    method: PUT
    status_code: 200
    body_format: json
    body:
      data:
        "{{ item.filename }}: {{ lookup('file', '{{ item.path }}' | base64 }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  with_items:
    - "{{ vault_kv_write_file_data }}"
  delegate_to: localhost