---
- name: Enable userpass auth engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/auth/userpass"
    method: POST
    status_code: [200, 400, 204]
    body_format: json
    body:
      type: userpass
      description: ""
      config: 
        options: null
        default_lease_ttl: 0s
        max_lease_ttl: 0s
        force_no_cache: false
      local: false
      seal_wrap: false
      external_entropy_access: false
      options: null
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create local vault user(s) via userpass engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/auth/userpass/users/{{ item.name }}"
    method: PUT
    status_code: 204
    body_format: json
    body:
      password: "{{ item.password }}"
      policies: "{{ item.policies }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  with_items:
    - "{{ vault_crate_user_data }}"
  delegate_to: localhost