---
- name: Enable vault secret engine for CA
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ vault_ca_path }}"
    method: POST
    body_format: json
    body:
      type: pki
      description: ""
      config: 
        options: null
        default_lease_ttl: 0s
        max_lease_ttl: 0s
        force_no_cache: false
      local: false
      seal_wrap: false
      external_entropy_access: false
      options: null
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Tune vault secret engine CA configuration
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ vault_ca_path }}/tune"
    method: POST
    body_format: json
    body:
      options: null
      default_lease_ttl: ""
      max_lease_ttl: "{{ vault_ca_max_lease_ttl }}"
      force_no_cache: false
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create ca root certificate
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/root/generate/internal"
    method: PUT
    body_format: json
    body:
      common_name: "{{ vault_ca_cert_common_name }}"
      key_bits: "{{ vault_ca_cert_key_bits }}"
      organization: "{{ vault_ca_cert_organization }}"
      ou: "{{ vault_ca_cert_ou }}"
      ttl: "{{ vault_ca_cert_ttl }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create ca and crl distribution points
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/config/urls"
    method: PUT
    body_format: json
    body:
      crl_distribution_points: "{{ vault_url }}/v1/pki/crl"
      issuing_certificates: "{{ vault_url }}/v1/pki/ca"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Create ca role (general certificate policy)
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}//roles/{{ vault_ca_cert_role_name }}"
    method: PUT
    body_format: json
    body:
      allow_subdomains: "{{ vault_ca_role_allow_subdomains }}"
      allowed_domains: "{{ vault_ca_role_allowed_domains }}"
      max_ttl: "{{ vault_ca_role_max_ttl }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Note
  ansible.builtin.debug:
    msg: "Please install the ca key on target system so that certificates classified as trusted. You can download the ca certificates for linux and windows here: {{ vault_url }}/ui/vault/settings/secrets/configure/{{ vault_ca_path }}/cert"