---
- name: Write KV data to kv secret engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ item.secret_engine }}/data/{{ item.secret_name }}"
    method: PUT
    status_code: 200
    body_format: json
    body: "{{ lookup('template', './vault-kv-write-secret.json.j2', template_vars=dict(data=item.kv)) }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  with_items:
    - "{{ vault_kv_write_data }}"
  delegate_to: "{{ vault_api_executor }}"
  when: vault_kv_write_data is defined

- name: Write file data in base64 to kv secret engine
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ item.secret_engine }}/data/{{ item.secret_name }}"
    method: PUT
    status_code: 200
    body_format: json
    body:
      data: 
        "{ '{{ item.filename }}': '{{ lookup('file', '{{ item.path }}') | b64encode }}'}" 
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  with_items:
    - "{{ vault_kv_write_file_data }}"
  delegate_to: "{{ vault_api_executor }}"
  when: vault_kv_write_file_data is defined

