---
- name: Create vault policy
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/policies/acl/{{ item.name }}"
    method: POST
    status_code: [204, 400]
    body_format: json
    body:
      policy: "{{ item.policy | b64encode }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  with_items:
    - "{{ vault_policies }}"
  delegate_to: "{{ vault_api_executor }}"