---
- name: Enable vault secret engine for CA
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ vault_ca_path }}"
    method: POST
    body_format: json
    body:
      type: pki
      description: ""
      config: 
        options: null
        default_lease_ttl: 0s
        max_lease_ttl: 0s
        force_no_cache: false
      local: false
      seal_wrap: false
      external_entropy_access: false
      options: null
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost

- name: Tune vault secret engine CA configuration
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/mounts/{{ vault_ca_path }}/tune"
    method: POST
    body_format: json
    body:
      options: null
      default_lease_ttl: ""
      max_lease_ttl: "{{ vault_ca_conf_max_lease_ttl }}"
      force_no_cache: false
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  delegate_to: localhost