---
- name: Load vault server podman-profile
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - 'vault-server.yaml'
      paths:
        - 'vars'

- name: Stop vault service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: stopped

- name: Cleanup vault volumes
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop:
    - { path: /podman/pv/vault-server }
