---
- name: "Request and sign certificate for {{ vault_gen_cert_fqdn }}"
  ansible.builtin.uri:
    return_content: yes
    validate_certs: false
    url: "{{ vault_url }}/v1/{{ vault_ca_path }}/issue/{{ vault_ca_cert_role_name }}"
    method: PUT
    body_format: json
    body:
      common_name: "{{ vault_gen_cert_fqdn }}"
    headers:
      X-Vault-Request: true
      X-Vault-Token: "{{ vault_token }}"
  register: vault_generated_cert
  delegate_to: localhost

- name: Installing public key
  ansible.builtin.copy:
    content: "{{ vault_generated_cert.json.certificate }}"
    dest: "{{ vault_gen_cert_install_pub_path }}"

- name: Installing private key
  ansible.builtin.copy:
    content: "{{ vault_generated_cert.json.certificate }}"
    dest: "{{ vault_gen_cert_install_priv_path }}"

- name: Output private key
  ansible.builtin.debug:
    msg: "Private KEY for {{ vault_gen_cert_fqdn }}: {{ vault_generated_cert.json.private_key }}"

- name: Output public key
  ansible.builtin.debug:
    msg: "Public KEY for {{ vault_gen_cert_fqdn }}: {{ vault_generated_cert.json.certificate }}"

- name: Output issuing ca public key
  ansible.builtin.debug:
    msg: "Public KEY of certification authority (please install): {{ vault_generated_cert.json.issuing_ca }}"

- name: Note
  ansible.builtin.debug:
    msg: "Please install the ca key on target system so that the issued certificate is classified as trusted"

- name: CA key linux link
  ansible.builtin.debug:
    msg: "CA key for linux - download here: {{ vault_url }}/v1/{{ vault_ca_path }}/ca/pem"

- name: CA key windows link
  ansible.builtin.debug:
    msg: "CA key for windows - download here: {{ vault_url }}/v1/{{ vault_ca_path }}/ca"