---
- name: Create GET method in bashrc for request secrets
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    state: present
    insertafter: EOF
    line: "{{ lookup('template', './bashrc.j2') }}"

- name: Note
  ansible.builtin.debug:
    msg: "After terminal restart or system reboot you can execute the alias name to source the vault vars to your env"
