---
- name: Request a vault init
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/init"
    method: POST
    status_code: 200
    body_format: json
    body:
      secret_shares: "{{ install_vault_init_secret_shares }}"
      secret_threshold: "{{ install_vault_init_secret_threshold }}"
  register: vault_api_data_init
  delegate_to: localhost

- name: Debug api init information
  ansible.builtin.debug:
    msg: "Token received from vault server: {{ vault_api_data_init }}"
  when: debug | bool