---
- name: "Wait for webservice {{ vault_url }} come up"
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}"
    status_code: 200
  register: vault_api_data_website_status
  until: vault_api_data_website_status.status == 200
  retries: 60
  delay: 1
  delegate_to: localhost

- name: Request a vault init
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}/v1/sys/init"
    method: POST
    status_code: 200
    body_format: json
    body:
      secret_shares: "{{ install_vault_init_secret_shares }}"
      secret_threshold: "{{ install_vault_init_secret_threshold }}"
  register: vault_api_data_init
  delegate_to: localhost

- name: Debug api init information
  ansible.builtin.debug:
    msg: "Init confirmation message from server: {{ vault_api_data_init.json }}"
  when: debug | bool

- name: Output root token
  ansible.builtin.debug:
    msg: "Generated root token: {{ vault_api_data_init.json.root_token }}"

- name: Output unseal key(s)
  ansible.builtin.debug:
    msg: "Generated unseal key(s): {{ vault_api_data_init.json }}"

- name: Note
  ansible.builtin.debug:
    msg: "Please go to: {{ vault_url }} and unseal the vault with the root token: {{ vault_api_data_init.json.root_token }}"