---
- name: Load vault server podman-profile
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - 'vault-server.yaml'
      paths:
        - 'vars'

- name: Create vault config dir
  ansible.builtin.file:
    path: "{{ mounts.config.host }}"
    state: directory

- name: Create vault configuration file
  ansible.builtin.template:
    src: "vault_config_{{ vault_storage_backend }}.json.j2"
    dest: "{{ mounts.config.host }}vault.json"

- name: Deploy Vault
  include_role:
    name: deploy-podman-container
