---
- name: Load vault server podman-profile
  ansible.builtin.include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - 'vault-server.yaml'
      paths:
        - 'vars'

- name: Set enterprice licence var for enterprise installation
  ansible.builtin.set_fact:
    env_vars:
      ENTERPRISE_KEY:
        key: VAULT_LICENSE
        value: "{{ vault_enterprise_licence }}"
  when: vault_product_type == 'enterprise'

- name: Create vault config dir
  ansible.builtin.file:
    path: "{{ mounts.config.host }}"
    state: directory

- name: Create vault configuration file on hosts
  ansible.builtin.template:
    src: "vault_config_{{ vault_storage_backend }}.json.j2"
    dest: "{{ mounts.config.host }}vault.json"

- name: Deploy Vault
  ansible.builtin.include_role:
    name: deploy-podman-container

- name: "Wait for webservice {{ vault_url }} come up"
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ vault_url }}"
    status_code: 200
  register: vault_api_data_website_status
  until: vault_api_data_website_status.status == 200
  retries: 60
  delay: 1
  delegate_to: "{{ vault_api_executor }}"
