---
- name: Install vault server
  include_tasks: install-vault.yaml
  when: install_vault|bool

- name: Authenticate to the vault server
  include_tasks: authentication.yml

- name: Create vault certification authority
  include_tasks: create_ca.yml
  when: vault_create_ca | bool

- name: Generate trusted certificate via vault server
  include_tasks: create_cert.yml
  when: vault_gen_cert | bool

- name: Create kv database
  include_tasks: create_kv_db.yml
  when: vault_create_kv_db | bool

- name: Write data to kv database
  include_tasks: create_write_kv.yml
  when: vault_kv_write | bool