---
- name: Authenticate to the vault server
  include_tasks: authentication.yml

- name: Create vault certification authority
  include_tasks: create_ca.yml
  when: vault_create_ca | bool

- name: Generate trusted certificate via vault server
  include_tasks: create_ca.yml
  when: vault_gen_cert | bool