---
- name: Install vault server
  include_tasks: install-vault.yaml
  when: install_vault|bool

- name: Init vault server after installation
  include_tasks: init-vault.yaml
  when: install_vault|bool

- name: Create user via userpass engine
  include_tasks: create-user.yaml
  when: vault_create_user|bool

- name: Authenticate to the vault server
  include_tasks: authentication.yaml
  when: vault_token is undefined and not install_vault

- name: Create vault certification authority
  include_tasks: create-ca.yaml
  when: vault_create_ca|bool

- name: Generate trusted certificate via vault server
  include_tasks: generate-cert.yaml
  when: vault_gen_cert|bool

- name: Create KV database
  include_tasks: create-kv-db.yaml
  when: vault_create_kv_db|bool

- name: Write data to KV database
  include_tasks: create-write-kv.yaml
  when: vault_kv_write|bool

- name: Install vault ca certificate to local system
  include_tasks: install-ca-auth.yaml
  when: vault_kv_write|bool