---
- name: Install vault CA to Debian os system
  ansible.builtin.shell: /usr/sbin/update-ca-certificates
  when: ansible_os_family == "Debian"

- name: Install vault CA to RedHat os system
  ansible.builtin.shell: /bin/update-ca-trust
  when: ansible_os_family == "RedHat"
